### ISSUE TITLE
Nativescript-Vue please

### ISSUE THREAD

**Issue by ukik** [arnasdev/nativescript-ez-accordion#2]
please how to use it on nativescript-vue

**Comment by arnasdev** [comment]
> please how to use it on nativescript-vue

Hey @ukik 

I took a quick look at converting this to nativescript-vue. I've never used Vue before so my implementation isn't as clean as the Angular version but it does work. 

I'll update the repo and clean up the Vue code further in the next few days but in the mean time here's a link to the Nativescript Playground where you can see this code:
https://play.nativescript.org/?template=play-vue&id=YANIBj&v=6
